# Generated by Django 5.0.3 on 2024-07-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_passwordchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordChange',
        ),
    ]
